package docker

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// HelperScriptOptions configures helper script generation
type HelperScriptOptions struct {
	WorktreePath string   // Path to new worktree
	ComposeFiles []string // Base compose files
	OverrideFile string   // Override file name (or empty for shared mode)
	ShellType    string   // "bash", "powershell", or "cmd"
}

// GenerateHelperScript creates the dc helper script
func GenerateHelperScript(opts HelperScriptOptions) error {
	shell := opts.ShellType
	if shell == "" {
		shell = getDefaultShell()
	}

	var scriptPath, scriptContent string

	switch shell {
	case "bash":
		scriptPath = filepath.Join(opts.WorktreePath, "dc")
		scriptContent = generateBashScript(opts)
	case "powershell":
		scriptPath = filepath.Join(opts.WorktreePath, "dc.ps1")
		scriptContent = generatePowerShellScript(opts)
	case "cmd":
		scriptPath = filepath.Join(opts.WorktreePath, "dc.cmd")
		scriptContent = generateCmdScript(opts)
	default:
		scriptPath = filepath.Join(opts.WorktreePath, "dc")
		scriptContent = generateBashScript(opts)
	}

	// Write script
	if err := os.WriteFile(scriptPath, []byte(scriptContent), 0755); err != nil {
		return err
	}

	return nil
}

// getDefaultShell returns the default shell for the current OS
func getDefaultShell() string {
	if runtime.GOOS == "windows" {
		// Check if running in Git Bash/MSYS
		if os.Getenv("MSYSTEM") != "" {
			return "bash"
		}
		return "cmd" // Default to cmd for broader compatibility
	}
	return "bash"
}

// generateBashScript generates a bash helper script
func generateBashScript(opts HelperScriptOptions) string {
	var sb strings.Builder

	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("# Auto-generated by gwt - convenience wrapper for docker-compose\n")
	sb.WriteString("# Usage: ./dc up, ./dc down, ./dc logs, etc.\n\n")

	// Build compose files list
	if opts.OverrideFile != "" {
		sb.WriteString("COMPOSE_FILES=\"")
		for _, f := range opts.ComposeFiles {
			sb.WriteString("-f ")
			sb.WriteString(filepath.Base(f))
			sb.WriteString(" ")
		}
		sb.WriteString("-f ")
		sb.WriteString(opts.OverrideFile)
		sb.WriteString("\"\n\n")
	} else {
		sb.WriteString("COMPOSE_FILES=\"")
		for _, f := range opts.ComposeFiles {
			sb.WriteString("-f ")
			sb.WriteString(filepath.Base(f))
			sb.WriteString(" ")
		}
		sb.WriteString("\"\n\n")
	}

	sb.WriteString("docker compose $COMPOSE_FILES \"$@\"\n")

	return sb.String()
}

// generatePowerShellScript generates a PowerShell helper script
func generatePowerShellScript(opts HelperScriptOptions) string {
	var sb strings.Builder

	sb.WriteString("# Auto-generated by gwt - convenience wrapper for docker-compose\n")
	sb.WriteString("# Usage: .\\dc.ps1 up, .\\dc.ps1 down, .\\dc.ps1 logs, etc.\n\n")

	// Build compose files array
	sb.WriteString("$ComposeFiles = @(")
	for _, f := range opts.ComposeFiles {
		sb.WriteString("\"-f\", \"")
		sb.WriteString(filepath.Base(f))
		sb.WriteString("\", ")
	}
	if opts.OverrideFile != "" {
		sb.WriteString("\"-f\", \"")
		sb.WriteString(opts.OverrideFile)
		sb.WriteString("\"")
	} else {
		// Remove trailing comma and space
		result := sb.String()
		result = strings.TrimSuffix(result, ", ")
		sb.Reset()
		sb.WriteString(result)
	}
	sb.WriteString(")\n\n")

	sb.WriteString("docker compose @ComposeFiles $args\n")

	return sb.String()
}

// generateCmdScript generates a CMD batch script
func generateCmdScript(opts HelperScriptOptions) string {
	var sb strings.Builder

	sb.WriteString("@echo off\n")
	sb.WriteString("REM Auto-generated by gwt - convenience wrapper for docker-compose\n")
	sb.WriteString("REM Usage: dc up, dc down, dc logs, etc.\n\n")

	// Build compose files
	sb.WriteString("docker compose")
	for _, f := range opts.ComposeFiles {
		sb.WriteString(" -f ")
		sb.WriteString(filepath.Base(f))
	}
	if opts.OverrideFile != "" {
		sb.WriteString(" -f ")
		sb.WriteString(opts.OverrideFile)
	}
	sb.WriteString(" %*\n")

	return sb.String()
}
