package docker

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestSanitizeBranchName(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{"Simple branch", "feature", "feature"},
		{"With slash", "feature/auth", "feature-auth"},
		{"With backslash", "feature\\auth", "feature-auth"},
		{"With spaces", "feature auth", "feature-auth"},
		{"With underscores", "feature_auth", "feature-auth"},
		{"Mixed case", "Feature/Auth", "feature-auth"},
		{"Multiple slashes", "feat/sub/auth", "feat-sub-auth"},
		{"Leading/trailing dash", "-feature-", "feature"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := sanitizeBranchName(tt.input)
			if result != tt.expected {
				t.Errorf("sanitizeBranchName(%s) = %s, expected %s", tt.input, result, tt.expected)
			}
		})
	}
}

func TestRenameVolume(t *testing.T) {
	tests := []struct {
		volumeName   string
		branchSuffix string
		expected     string
	}{
		{"postgres_data", "feature-auth", "postgres_data_feature-auth"},
		{"redis_data", "main", "redis_data_main"},
		{"app_storage", "dev", "app_storage_dev"},
	}

	for _, tt := range tests {
		t.Run(tt.volumeName, func(t *testing.T) {
			result := renameVolume(tt.volumeName, tt.branchSuffix)
			if result != tt.expected {
				t.Errorf("renameVolume(%s, %s) = %s, expected %s",
					tt.volumeName, tt.branchSuffix, result, tt.expected)
			}
		})
	}
}

func TestOffsetPort(t *testing.T) {
	tests := []struct {
		port     int
		offset   int
		expected int
	}{
		{5432, 1, 5433},
		{8080, 10, 8090},
		{3000, 100, 3100},
	}

	for _, tt := range tests {
		result := offsetPort(tt.port, tt.offset)
		if result != tt.expected {
			t.Errorf("offsetPort(%d, %d) = %d, expected %d",
				tt.port, tt.offset, result, tt.expected)
		}
	}
}

func TestIsCommonPort(t *testing.T) {
	tests := []struct {
		port     int
		expected bool
	}{
		{80, true},
		{443, true},
		{5432, true},
		{3306, true},
		{12345, false},
		{9999, false},
	}

	for _, tt := range tests {
		result := isCommonPort(tt.port)
		if result != tt.expected {
			t.Errorf("isCommonPort(%d) = %v, expected %v", tt.port, result, tt.expected)
		}
	}
}

func TestGenerateOverride(t *testing.T) {
	tmpDir := t.TempDir()

	// Create original config
	originalConfig := &ComposeConfig{
		Services: map[string]Service{
			"db": {
				Image: "postgres:14",
				Volumes: []string{
					"postgres_data:/var/lib/postgresql/data",
				},
				Ports: []string{
					"5432:5432",
				},
			},
			"redis": {
				Image: "redis:7",
				Volumes: []string{
					"redis_data:/data",
				},
				Ports: []string{
					"6379:6379",
				},
			},
		},
		Volumes: map[string]VolumeConfig{
			"postgres_data": {
				Name: "postgres_data",
			},
			"redis_data": {
				Name: "redis_data",
			},
		},
	}

	outputPath := filepath.Join(tmpDir, "docker-compose.worktree.yml")

	result, err := GenerateOverride(OverrideOptions{
		BranchName:     "feature/auth",
		OriginalConfig: originalConfig,
		PortOffset:     1,
		OutputPath:     outputPath,
	})

	if err != nil {
		t.Fatalf("GenerateOverride failed: %v", err)
	}

	// Check renamed volumes
	if len(result.RenamedVolumes) != 2 {
		t.Errorf("Expected 2 renamed volumes, got %d", len(result.RenamedVolumes))
	}

	expectedVolumeName := "postgres_data_feature-auth"
	if result.RenamedVolumes["postgres_data"] != expectedVolumeName {
		t.Errorf("Expected volume name %s, got %s",
			expectedVolumeName, result.RenamedVolumes["postgres_data"])
	}

	// Check remapped ports
	if len(result.RemappedPorts) != 2 {
		t.Errorf("Expected 2 remapped ports, got %d", len(result.RemappedPorts))
	}

	if result.RemappedPorts["5432"] != 5433 {
		t.Errorf("Expected port 5433, got %d", result.RemappedPorts["5432"])
	}

	// Check file was created
	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Error("Override file was not created")
	}

	// Read and parse the file
	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read override file: %v", err)
	}

	// Check header
	content := string(data)
	if !strings.Contains(content, "Auto-generated by gwt") {
		t.Error("Expected header comment in override file")
	}
	if !strings.Contains(content, "feature/auth") {
		t.Error("Expected branch name in override file")
	}

	// Parse YAML to verify structure
	var overrideConfig ComposeConfig
	if err := yaml.Unmarshal(data, &overrideConfig); err != nil {
		t.Fatalf("Failed to parse override YAML: %v", err)
	}

	// Check volumes section
	if len(overrideConfig.Volumes) != 2 {
		t.Errorf("Expected 2 volumes in override, got %d", len(overrideConfig.Volumes))
	}

	// Check services section
	if len(overrideConfig.Services) != 2 {
		t.Errorf("Expected 2 services in override, got %d", len(overrideConfig.Services))
	}

	// Check db service has renamed volume
	dbService := overrideConfig.Services["db"]
	if len(dbService.Volumes) != 1 {
		t.Errorf("Expected 1 volume in db service, got %d", len(dbService.Volumes))
	} else {
		if !strings.Contains(dbService.Volumes[0], "postgres_data_feature-auth") {
			t.Errorf("Expected renamed volume in db service, got %s", dbService.Volumes[0])
		}
	}

	// Check db service has remapped port
	if len(dbService.Ports) != 1 {
		t.Errorf("Expected 1 port in db service, got %d", len(dbService.Ports))
	} else {
		if !strings.HasPrefix(dbService.Ports[0], "5433:") {
			t.Errorf("Expected port 5433, got %s", dbService.Ports[0])
		}
	}
}

func TestGenerateOverrideWithPortWarnings(t *testing.T) {
	tmpDir := t.TempDir()

	// Create config that will generate port warnings
	originalConfig := &ComposeConfig{
		Services: map[string]Service{
			"web": {
				Ports: []string{
					"79:80", // Will become 80 (common port)
				},
			},
		},
		Volumes: map[string]VolumeConfig{},
	}

	outputPath := filepath.Join(tmpDir, "docker-compose.worktree.yml")

	result, err := GenerateOverride(OverrideOptions{
		BranchName:     "test",
		OriginalConfig: originalConfig,
		PortOffset:     1,
		OutputPath:     outputPath,
	})

	if err != nil {
		t.Fatalf("GenerateOverride failed: %v", err)
	}

	// Should have port warning for port 80
	if len(result.PortWarnings) == 0 {
		t.Error("Expected port warnings but got none")
	}
}
