package docker

import (
	"fmt"
	"os"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// OverrideOptions configures override file generation
type OverrideOptions struct {
	BranchName     string         // Branch name for suffix
	OriginalConfig *ComposeConfig // Original compose config
	PortOffset     int            // Port offset from config
	OutputPath     string         // Where to write override file
}

// OverrideResult reports what was generated
type OverrideResult struct {
	FilePath       string
	RenamedVolumes map[string]string // original -> renamed
	RemappedPorts  map[string]int    // original:new
	PortWarnings   []string          // Potential conflicts
}

var commonPorts = map[int]string{
	80:    "HTTP",
	443:   "HTTPS",
	3000:  "Node.js/React dev server",
	3306:  "MySQL",
	5432:  "PostgreSQL",
	5433:  "PostgreSQL (alternate)",
	6379:  "Redis",
	8080:  "HTTP alternate",
	8443:  "HTTPS alternate",
	27017: "MongoDB",
}

// GenerateOverride creates a docker-compose.worktree.yml file
func GenerateOverride(opts OverrideOptions) (*OverrideResult, error) {
	result := &OverrideResult{
		RenamedVolumes: make(map[string]string),
		RemappedPorts:  make(map[string]int),
	}

	branchSuffix := sanitizeBranchName(opts.BranchName)
	override := &ComposeConfig{
		Services: make(map[string]Service),
		Volumes:  make(map[string]VolumeConfig),
	}

	// 1. Process named volumes
	for volName := range opts.OriginalConfig.Volumes {
		newName := renameVolume(volName, branchSuffix)
		result.RenamedVolumes[volName] = newName
		override.Volumes[newName] = VolumeConfig{
			Name: newName,
		}
	}

	// 2. Process services
	for svcName, svc := range opts.OriginalConfig.Services {
		overrideSvc := Service{}
		modified := false

		// Rename volume references
		for _, vol := range svc.Volumes {
			mount := parseVolumeMount(vol, svcName)
			if mount.IsNamed {
				if newName, ok := result.RenamedVolumes[mount.Source]; ok {
					volStr := fmt.Sprintf("%s:%s", newName, mount.Target)
					if mount.IsReadOnly {
						volStr += ":ro"
					}
					overrideSvc.Volumes = append(overrideSvc.Volumes, volStr)
					modified = true
				}
			}
		}

		// Offset ports
		for _, port := range svc.Ports {
			mapping := parsePortMapping(port, svcName)
			if mapping.HostPort > 0 {
				newPort := offsetPort(mapping.HostPort, opts.PortOffset)
				result.RemappedPorts[fmt.Sprintf("%d", mapping.HostPort)] = newPort

				// Check for common conflicts
				if isCommonPort(newPort) {
					result.PortWarnings = append(result.PortWarnings,
						fmt.Sprintf("Port %d may conflict with common services (%s)", newPort, commonPorts[newPort]))
				}

				portStr := fmt.Sprintf("%d:%d", newPort, mapping.ContainerPort)
				if mapping.Protocol != "tcp" {
					portStr += "/" + mapping.Protocol
				}
				overrideSvc.Ports = append(overrideSvc.Ports, portStr)
				modified = true
			}
		}

		if modified {
			override.Services[svcName] = overrideSvc
		}
	}

	// 3. Write file
	result.FilePath = opts.OutputPath
	if err := writeOverrideFile(override, opts); err != nil {
		return nil, err
	}

	return result, nil
}

// sanitizeBranchName converts branch name to safe suffix
// "feature/auth" -> "feature-auth"
func sanitizeBranchName(branch string) string {
	// Replace path separators and special characters
	sanitized := strings.ReplaceAll(branch, "/", "-")
	sanitized = strings.ReplaceAll(sanitized, "\\", "-")
	sanitized = strings.ReplaceAll(sanitized, " ", "-")
	sanitized = strings.ReplaceAll(sanitized, "_", "-")

	// Convert to lowercase for consistency
	sanitized = strings.ToLower(sanitized)

	// Remove leading/trailing dashes
	sanitized = strings.Trim(sanitized, "-")

	return sanitized
}

// renameVolume generates new volume name with branch suffix
// "postgres_data" -> "postgres_data_feature-auth"
func renameVolume(volumeName, branchSuffix string) string {
	return fmt.Sprintf("%s_%s", volumeName, branchSuffix)
}

// offsetPort calculates new port with offset
func offsetPort(port, offset int) int {
	return port + offset
}

// isCommonPort checks if a port is in the common ports list
func isCommonPort(port int) bool {
	_, exists := commonPorts[port]
	return exists
}

// writeOverrideFile writes the override config to a YAML file with header
func writeOverrideFile(config *ComposeConfig, opts OverrideOptions) error {
	// Marshal YAML
	data, err := yaml.Marshal(config)
	if err != nil {
		return &DockerError{
			Op:   "marshal",
			File: opts.OutputPath,
			Err:  err,
		}
	}

	// Create header
	header := fmt.Sprintf(`# Auto-generated by gwt - do not edit manually
# To use: docker compose -f docker-compose.yml -f docker-compose.worktree.yml up
#
# Generated for branch: %s
# Generated at: %s

`, opts.BranchName, time.Now().Format(time.RFC3339))

	// Combine header and YAML
	fullContent := header + string(data)

	// Write file
	if err := os.WriteFile(opts.OutputPath, []byte(fullContent), 0644); err != nil {
		return &DockerError{
			Op:   "write",
			File: opts.OutputPath,
			Err:  err,
		}
	}

	return nil
}
